# NumPy Examples

In [1]:
import numpy as np

### Arrays

In [3]:
# 1D numpy array, basically just a list
a = np.array([2, 3, 4]) # You must give np.array a list, hence why there are sq brackets in parentheses.
a

array([2, 3, 4])

In [5]:
# 2D numpy array
b = np.array([2, 3, 4, 5, 6, 2]).reshape(2, 3) # The reshape method turns an array into .reshape(rows, columns)
b

array([[2, 3, 4],
       [5, 6, 2]])

In [6]:
# 3D numpy array
c = np.array([2, 3, 4, 5, 6, 2, 3, 5]).reshape(2,2,2)
c

array([[[2, 3],
        [4, 5]],

       [[6, 2],
        [3, 5]]])

### NumPy Calculations

In [11]:
d = np.array([1, 2, 3, 4, 5, 6])
print('sum =', d.sum())
print('min =', d.min())
print('max =', d.max())
print('mean =', d.mean())

sum = 21
min = 1
max = 6
mean = 3.5


### Special Arrays

In [19]:
np.zeros(5) # Creates an array of zeros
np.ones(5) # Creates an array of ones
np.linspace(0,100,13) # Creates an array from 0 to 100 with 13 envenly spaces observations
np.random.rand(3) # Three random values between 0 and 1
np.random.randint(1, 1000) # One random integer between 1 and 1000
np.arange(0,100,5) # Like base python range function

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])